
//HASHING - used to map key value set on indices generated by hashing function.
// searching is faster and done in constant time.

/*IMPORTANT THEORY TERMINOLOGIES
* Hash function.
* Hash table.
* Hash technique--- Open addressing , Chaining(creates array list at collision index),
* Load factor. */

package com.company;
import java.util.HashSet;
public class CWH_43_HashSet {
        public static void main(String[] args) {
            HashSet<Integer> myHashSet = new HashSet<>(6, 0.5f);
            myHashSet.add(6);
            myHashSet.add(8);
            myHashSet.add(3);
            myHashSet.add(11);
            myHashSet.add(11);
            System.out.println(myHashSet);
        }
    }
